baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Agile Paradigm Wiki'
theme = 'hextra'

[module]
  [[module.imports]]
    path = 'github.com/imfing/hextra'

# Main menu configuration to reflect the Diátaxis framework
[[menu.main]]
  name = "Tutorials"
  pageRef = "/tutorials"
  weight = 1

[[menu.main]]
  name = "How-To Guides"
  pageRef = "/how-to"
  weight = 2

[[menu.main]]
  name = "Explanation"
  pageRef = "/explanation"
  weight = 3

[[menu.main]]
  name = "Reference"
  pageRef = "/reference"
  weight = 4

[[menu.main]]
  name = "Search"
  weight = 5
[menu.main.params]
  type = 'search'

enableGitInfo = true

[params]
  displayUpdatedDate = true
  dateFormat = 'January 2, 2006'
  externalLinkDecoration = true
[params.toc]
  displayTags = true
[params.navbar]
  displayTitle = false
  displayLogo = true 
[params.navbar.logo]
  path = 'logo.png'
  link = '/'
  width = 180
  height = 30
[params.footer]
  displayCopyright = true
  displayPoweredBy = false
